Models/Video.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProjectItiTeam.Models
{
    public class Video
    {
        [Key]
        public int ID { get; set; }

        [Required]
        [StringLength(30)]
        public string Name { get; set; }

        [StringLength(90)]
        public string Description { get; set; }

        [StringLength(90)]
        public string VideoUrl { get; set; }

        [ForeignKey("Course")]
        public int Course_ID { get; set; }
        public int User_Id { get; set; }
        public string username { get; set; }
        public string pathViedoes { get; set; }

        public virtual Course Course { get; set; }

    }
}
 

Controllers/VideoController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProjectItiTeam.Models;
using ProjectItiTeam.Repository;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace ProjectItiTeam.Controllers
{
    public class VideoController : Controller
    {
        IVideoRepository VideoRepository;//=new VideoRepository();
        ICourseRepository CourseRepository;//=new CourseRepository();
        private readonly IWebHostEnvironment webHostEnvironment;

        public VideoController(IVideoRepository videoRepo, ICourseRepository courseRepo, IWebHostEnvironment WebHostEnvironment)
        {
            VideoRepository = videoRepo;
            CourseRepository = courseRepo;
            webHostEnvironment = WebHostEnvironment;
        }

        public IActionResult testGuid()
        {

            ViewBag.id = VideoRepository.id;
            return View();
        }
        //Index
        public IActionResult Index()
        {
            List<Video> video = VideoRepository.GetAll();
            return View("Index", video);
        }
        //Details
        public IActionResult Details(int Id)
        {
            Video video =
                 VideoRepository.GetById(Id);

            return View("Details", video);
        }
        //New

        public IActionResult New()
        {
            ViewData["Course_ID"] = new SelectList(CourseRepository.GetAll(), "Id", "Name");
            return View("New", new Video());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SaveNew(Video video)
        {
            if (ModelState.IsValid)
            {
                string VidPAth = @"\PathVideos\default.png";
                var files = HttpContext.Request.Form.Files;
                if (files.Count() > 0)
                {
                    Guid d = Guid.NewGuid();

                    string host = webHostEnvironment.WebRootPath;
                    string ImageName = DateTime.Now.ToFileTime().ToString() + Path.GetExtension(files[0].FileName);
                    FileStream fileStream = new FileStream(Path.Combine(host, "PathVideos", d + ImageName), FileMode.Create);
                    files[0].CopyTo(fileStream);

                    VidPAth = @"\PathVideos\" + d + ImageName;
                }
                video.pathViedoes = VidPAth;
            }

            if (video.Name != null && video.Course_ID != 0)
            {
                VideoRepository.Insert(video);
                return RedirectToAction("Index");
            }
            ViewData["Course_ID"] = new SelectList(CourseRepository.GetAll(), "Id", "Name");

            return View("New", video);
        }
        //Edit
        public IActionResult Edit(int id)
        {
            Video video = VideoRepository.GetById(id);
            List<Course> courses = CourseRepository.GetAll();
            ViewBag.crs = courses.ToList();
            ViewData["Course_ID"] = new SelectList(CourseRepository.GetAll(), "Id", "Name");

            return View("Edit", video);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SaveEdit([FromRoute] int id, Video video)
        {
            if (ModelState.IsValid)
            {
                string VidPAth = @"\PathVideos\default.png";
                var files = HttpContext.Request.Form.Files;
                if (files.Count() > 0)
                {
                    Guid d = Guid.NewGuid();

                    string host = webHostEnvironment.WebRootPath;
                    string ImageName = DateTime.Now.ToFileTime().ToString() + Path.GetExtension(files[0].FileName);
                    FileStream fileStream = new FileStream(Path.Combine(host, "PathVideos", d + ImageName), FileMode.Create);
                    files[0].CopyTo(fileStream);

                    VidPAth = @"\PathVideos\" + d + ImageName;
                }
                video.pathViedoes = VidPAth;
            }
            if (video.Name != null)
            {
                VideoRepository.update(id, video);
                return RedirectToAction("Index");
            }
            List < Course > courses = CourseRepository.GetAll();
            ViewBag.crs = courses.ToList();
            ViewData["Course_ID"] = new SelectList(CourseRepository.GetAll(), "Id", "Name");

            return View("Edit", video);
        }

        //Delete
        public IActionResult Delete(int id)
        {
            Video video = VideoRepository.GetById(id);
            return View("Delete", video);
        }

        [HttpPost]
        public IActionResult SaveDelete(int id)
        {
            VideoRepository.delete(id);
            return RedirectToAction("Index");

        }
    }
}

Views/Video/Delete.cshtml
@model ProjectItiTeam.Models.Video

@{
    ViewData["Title"] = "Delete" +  Model.Name;
}

<h1>Delete @Model.Name</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User_Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User_Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Course)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Course.Name)
        </dd class>

    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Video/Details.cshtml
@model Video

<div class="container marginTop">
    <div class="row">
        <div class="card" style="padding:1rem;">
            <div class="text-center view overlay hm-white-slight">
                <div class="videoplayer" id="myCustomPlayer">
   <div class="ratio ratio-16x9 bg-dark">
@*      <video class="video" src="@Model.VideoUrl"></video>
*@            <iframe class="embed-responsive-item video" src="@Model.VideoUrl"  allowfullscreen></iframe>

            </div>
            <div class="card-block">
                <!--Title-->
                <h4 class="card-title" style="color:green">@Model.Name</h4>
                <!--Text-->
                <p class="card-text">@Model.Description.</p>
                <p class="btn btn-group pull-right">
                    
                    <div class="btn-group ">
                        <a class="btn btn-success" asp-controller="Video" asp-action="Index">Show all Videos</a>
                    </div>
                   <div class="btn-group ">
                        <a class="btn btn-default btn-outline-success" style="background-color: white; color: green;" asp-controller="Video" asp-action="Index">Add To Dashboard</a>
                    </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>

Views/Video/Edit.cshtml
@model ProjectItiTeam.Models.Video

@{
    ViewData["Title"] = "Update -" + Model.Name;
}

<h1>Update @Model.Name</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="SaveEdit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-success"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-success"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-success"></span>
            </div>
            <div class="form-group">
                <div class="form-group">
                    <label asp-for="Course.Name" class="control-label"></label>
                    <select asp-for="Course_ID" class ="form-control" asp-items="ViewBag.Course_ID"></select>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="User_Id" class="control-label"></label>
                <input asp-for="User_Id" class="form-control" />
                <span asp-validation-for="User_Id" class="text-success"></span>
            </div>
             <div class="form-group">
                        <label asp-for="pathViedoes" class="control-label"></label>
                        <input type="file" asp-for="pathViedoes" class="form-control" />
                        <span asp-validation-for="pathViedoes" class="text-danger"></span>
             </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Video/Index.cshtml
@model IEnumerable<ProjectItiTeam.Models.Video>



@if (User.IsInRole("Admin"))
{
    <div class="row " style="margin-top: 1%;text-align: left;">
        <div class="col-lg-12 col-md-12 my-4 text-center">
            <a href="/Video/New" class="btn btn-info form-control w-50 text-light"><strong>Add Video</strong></a>
        </div>
    </div>
}

<div class="row marginTop row">
    @foreach (var video in Model)
    {
         <div class="p-2 box-shadow rounded border col-md-4 col-12">
            <video controls width="100%" height="100%">

            <source src="@video.pathViedoes" type="video/mp4">
            <source src="@video.pathViedoes" type="audio/ogg">
            </video>
          </div>
        @Html.Partial("_VideoSummary", video)
    }
</div>

Views/Video/New.cshtml
@*@model ProjectItiTeam.Data.ViewModels.NewVideoViewModel
*@
@using ProjectItiTeam.Data.Enums;
@model Video
@{
    Layout="_LayoutCourseDetails";
}

<div class="bg-image" 
     style="background-image: url('~/PhotoUser/banaar.jpg');
            height: 100vh">

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4 class="text-success box-shadow p-1 rounded ">Create a new Video</h4>
        </p>

        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="SaveNew" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control"/>
                                <span asp-validation-for="Name" class="text-success"></span>
                            </div>
                            </div>
                        
                        <div class="col-md-6">
                           <div class="form-group">
                                <label asp-for="Course.Name" class="control-label">Course</label>
                                <select asp-for="Course_ID" class ="form-control" asp-items="ViewBag.Course_ID"></select>
                            </div>
                            
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="VideoUrl" class="control-label"></label>
                                <input asp-for="VideoUrl" class="form-control"/>
                                <span asp-validation-for="VideoUrl" class="text-success"></span>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <input asp-for="Description" class="form-control" />
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4 offset-4 text-center">
@*                        <img width="100%" id="ImageUrlPreview" />
*@                        <video width="100%" id="ImageUrlPreview"  autoplay loop alt="Video-Course"></video>
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-outline-primary float-right" />
                        <a class="btn btn-outline-light" asp-action="Index">Show All</a>
                    </div>
                    
                </form>
            </div>
        </div>
    </div>
</div>
</div>